### ISSUE TITLE
flask_migrate not found in trying to run the frontend

### ISSUE THREAD

**Issue by vwhu** [ECSHackWeek/ECSBatteryDatabase#4]
Getting this error message back when trying to execute python application.py

Traceback (most recent call last):
  File "../application.py", line 2, in <module>
    from server import application
  File "C:\Users\victor\ECSBatteryDatabase\frontend\server\__init__.py", line 3, in <module>
    from flask_migrate import Migrate
ModuleNotFoundError: No module named 'flask_migrate'

**Comment by mdmurbach** [comment]
looks like you need to install it `pip install Flask-Migrate`

**Comment by mdmurbach** [comment]
also, I don't think the frontend (js) of the frontend (flask) does anything yet :smiley: i was just playing around with the orm/database
